# Generated by Django 5.0.1 on 2024-02-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
